app:app.c addition.c subtract.c multiplication.c division.c modulus.c arith.h
	gcc app.c -o app libarith.so.1
addition.o:addition.c
	gcc -c addition.c -o addition.o
subtract.o:subtract.c
	gcc -c subtract.c -o subtract.o
multiplication.o:multiplication.c
	gcc -c multiplication.c -o multiplication.o
division.o:division.c
	gcc -c division.c -o division.o
modulus:modulus.c
	gcc -c modulus.c -o modulus.o

